# Generated by Django 3.0.5 on 2021-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
