# Generated by Django 3.0.5 on 2021-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210331_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
