# Generated by Django 3.0.5 on 2021-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210414_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='texto',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
