# Generated by Django 3.0.5 on 2021-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210420_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('video1', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video2', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video3', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video4', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
