# Generated by Django 3.0.5 on 2021-05-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='curso',
            name='video1',
            field=models.URLField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='curso',
            name='video2',
            field=models.URLField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='curso',
            name='video3',
            field=models.URLField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='curso',
            name='video4',
            field=models.URLField(null=True, verbose_name=''),
        ),
    ]
