# Generated by Django 3.0.5 on 2021-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210510_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='video3',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='video4',
        ),
        migrations.AlterField(
            model_name='curso',
            name='video1',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
