# Generated by Django 3.0.5 on 2021-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210510_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video2',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='video3',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='video4',
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
