# Generated by Django 3.0.5 on 2021-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210510_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cripto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='forex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='otro',
            field=models.BooleanField(default=False),
        ),
    ]
